import { CategoryType, CategoryInfo, StuffyBadge } from './types';

export const CATEGORIES: CategoryInfo[] = [
  {
    id: CategoryType.ADDITION,
    title: 'Bigger Addition',
    icon: '➕',
    color: 'bg-blue-600',
    description: 'Master rounding & splitting!',
    example: '68 + 47 → 68 + 50 - 3 = 115'
  },
  {
    id: CategoryType.SUBTRACTION,
    title: 'Multi-Step Subtraction',
    icon: '➖',
    color: 'bg-rose-600',
    description: 'Try the "Counting Up" strategy.',
    example: '250 - 97 → 97 + 3 = 100, then + 150 = 153'
  },
  {
    id: CategoryType.MULT_BREAKDOWN,
    title: 'Mental Breakdown',
    icon: '✖️',
    color: 'bg-amber-500',
    description: 'Split numbers to multiply easier.',
    example: '23 × 5 = (20 × 5) + (3 × 5) = 115'
  },
  {
    id: CategoryType.MULT_NEAR,
    title: 'Near-10 Mastery',
    icon: '🎯',
    color: 'bg-emerald-600',
    description: 'Use 10s and 100s as your anchor.',
    example: '19 × 6 = (20 × 6) - 6 = 114'
  },
  {
    id: CategoryType.MULT_SQUARE,
    title: 'Perfect Squares',
    icon: '🔲',
    color: 'bg-teal-600',
    description: 'Multiply a number by itself!',
    example: '25 × 25 = (20 × 30) + 25 = 625'
  },
  {
    id: CategoryType.DIVISION,
    title: 'Division Explorer',
    icon: '➗',
    color: 'bg-indigo-600',
    description: 'Find the facts and the remainders.',
    example: '65 ÷ 6 = (6 × 10) + 5'
  },
  {
    id: CategoryType.FRACTIONS,
    title: 'Fraction Power',
    icon: '🧩',
    color: 'bg-purple-600',
    description: 'Halves, Quarters, and Three Quarters.',
    example: 'Quarter of 80 = 80 ÷ 4 = 20'
  },
  {
    id: CategoryType.ESTIMATION,
    title: 'Estimation Champ',
    icon: '🔢',
    color: 'bg-orange-600',
    description: 'Build your "Number Sense".',
    example: '49 + 73 ≈ 50 + 70 = 120'
  }
];

// ── Badge catalog: Spooky Study + Galaxy Lab sets ──
export const STUFFY_BADGES: StuffyBadge[] = [
  // Spooky Study Set
  {
    id: 'milk_teeth_medal',
    setId: 'spooky_study',
    name: 'Milk Teeth Medal',
    slot: 'body',
    rarity: 'common',
    description: 'A chunky milk-tooth necklace that clacks when you move.',
    lore: 'You bit into math for the first time.',
    emoji: '🦷',
  },
  {
    id: 'brain_melt_marshmallow_lv1',
    setId: 'spooky_study',
    name: 'Brain Melt Marshmallow',
    slot: 'body',
    rarity: 'common',
    description: 'A slightly burnt marshmallow stuck to your head, looking tired but proud.',
    lore: 'Your brain melted a little, but you stayed.',
    emoji: '🍡',
    evolvesTo: 'brain_melt_marshmallow_lv2',
  },
  {
    id: 'brain_melt_marshmallow_lv2',
    setId: 'spooky_study',
    name: 'Brain Melt Marshmallow (Double Stack)',
    slot: 'body',
    rarity: 'rare',
    description: 'Two stacked marshmallows: one sleepy, one hyper.',
    lore: 'You’ve stayed in the fire long enough to toast a friend.',
    emoji: '🍢',
    evolvesTo: 'brain_melt_marshmallow_lv3',
  },
  {
    id: 'brain_melt_marshmallow_lv3',
    setId: 'spooky_study',
    name: 'Marshmallow Crown',
    slot: 'head',
    rarity: 'rare',
    description: 'A full ring of marshmallows hovering like a halo.',
    lore: 'Your study sessions are a campfire that never goes out.',
    emoji: '👑',
  },
  {
    id: 'night_owl_crown',
    setId: 'spooky_study',
    name: 'Night Owl Crown',
    slot: 'head',
    rarity: 'rare',
    description: 'A crooked crown made of bitten crescent moons and sleepy stars.',
    lore: 'You kept the lights on when everyone else went to sleep.',
    emoji: '🦉',
  },
  {
    id: 'chaos_eyes',
    setId: 'spooky_study',
    name: 'Chaos Eyes',
    slot: 'face',
    rarity: 'rare',
    description: 'One spiral eye, one star eye, always a bit jittery.',
    lore: 'You kept going even when your brain felt scrambled.',
    emoji: '👀',
  },
  {
    id: 'oopsie_bandage',
    setId: 'spooky_study',
    name: 'Oopsie Bandage',
    slot: 'body',
    rarity: 'common',
    description: 'A big bandage with a doodled smiley slapped across your cheek.',
    lore: 'Falling on your face is still moving forward.',
    emoji: '🩹',
  },
  {
    id: 'slice_and_dice_halo',
    setId: 'spooky_study',
    name: 'Slice & Dice Halo',
    slot: 'aura',
    rarity: 'rare',
    description: 'A halo of pizza, fruit, and cake slices orbiting your head.',
    lore: 'You cut every fraction into perfect pieces.',
    emoji: '🍕',
  },
  {
    id: 'shadow_study_buddy',
    setId: 'spooky_study',
    name: 'Shadow Study Buddy',
    slot: 'aura',
    rarity: 'secret',
    description: 'A tiny shadow-double that follows a frame behind you.',
    lore: 'Another you also shows up when it’s hard.',
    emoji: '👥',
  },

  // Galaxy Lab Set
  {
    id: 'starlight_goggles',
    setId: 'galaxy_lab',
    name: 'Starlight Goggles',
    slot: 'face',
    rarity: 'common',
    description: 'Glowing goggles that let you see patterns in the stars.',
    lore: 'You started looking past the answer to see the structure.',
    emoji: '🥽',
  },
  {
    id: 'orbiting_notebook',
    setId: 'galaxy_lab',
    name: 'Orbiting Notebook',
    slot: 'aura',
    rarity: 'rare',
    description: 'A tiny notebook that orbits you, pages flipping on its own.',
    lore: 'Every hard problem left a satellite note behind.',
    emoji: '📔',
  },
  {
    id: 'gravity_boots',
    setId: 'galaxy_lab',
    name: 'Gravity Boots',
    slot: 'body',
    rarity: 'common',
    description: 'Heavy boots that keep you grounded in long, tough sets.',
    lore: 'You didn’t float away when the problems got heavy.',
    emoji: '🥾',
  },
  {
    id: 'quantum_pocket_watch',
    setId: 'galaxy_lab',
    name: 'Quantum Pocket Watch',
    slot: 'body',
    rarity: 'rare',
    description: 'A watch that ticks faster when you think faster.',
    lore: 'You bent time by staying accurate at speed.',
    emoji: '⌚️',
  },
  {
    id: 'nebula_coat',
    setId: 'galaxy_lab',
    name: 'Nebula Coat',
    slot: 'body',
    rarity: 'rare',
    description: 'A lab coat made of swirling nebula clouds.',
    lore: 'You solved enough problems to make your own constellation.',
    emoji: '🧥',
  },
  {
    id: 'black_hole_backpack',
    setId: 'galaxy_lab',
    name: 'Black Hole Backpack',
    slot: 'body',
    rarity: 'secret',
    description: 'A backpack that swallows all your mistakes into tiny stars.',
    lore: 'Every error became fuel for something brighter.',
    emoji: '🎒',
  },
  {
    id: 'comet_tail_aura',
    setId: 'galaxy_lab',
    name: 'Comet Tail',
    slot: 'aura',
    rarity: 'rare',
    description: 'A bright comet tail that follows every time you move.',
    lore: 'Your streak burned a path across the sky.',
    emoji: '☄️',
  },
  {
    id: 'alien_theorem_hat',
    setId: 'galaxy_lab',
    name: 'Alien Theorem Hat',
    slot: 'head',
    rarity: 'secret',
    description: 'A squishy alien thinking cap with glowing symbols.',
    lore: 'You solved enough hard puzzles that something from elsewhere took notice.',
    emoji: '👽',
  },
];
