import { CategoryType, CategoryInfo, StuffyBadge } from './types';

export const CATEGORIES: CategoryInfo[] = [
  {
    id: CategoryType.ADDITION,
    title: 'Bigger Addition',
    icon: '➕',
    color: 'bg-blue-600',
    description: 'Master rounding & splitting!',
    example: '68 + 47 → 68 + 50 - 3 = 115'
  },
  {
    id: CategoryType.SUBTRACTION,
    title: 'Multi-Step Subtraction',
    icon: '➖',
    color: 'bg-rose-600',
    description: 'Try the "Counting Up" strategy.',
    example: '250 - 97 → 97 + 3 = 100, then + 150 = 153'
  },
  {
    id: CategoryType.MULT_BREAKDOWN,
    title: 'Mental Breakdown',
    icon: '✖️',
    color: 'bg-amber-500',
    description: 'Split numbers to multiply easier.',
    example: '23 × 5 = (20 × 5) + (3 × 5) = 115'
  },
  {
    id: CategoryType.MULT_NEAR,
    title: 'Near-10 Mastery',
    icon: '🎯',
    color: 'bg-emerald-600',
    description: 'Use 10s and 100s as your anchor.',
    example: '19 × 6 = (20 × 6) - 6 = 114'
  },
  {
    id: CategoryType.MULT_SQUARE,
    title: 'Perfect Squares',
    icon: '🔲',
    color: 'bg-teal-600',
    description: 'Multiply a number by itself!',
    example: '25 × 25 = (20 × 30) + 25 = 625'
  },
  {
    id: CategoryType.DIVISION,
    title: 'Division Explorer',
    icon: '➗',
    color: 'bg-indigo-600',
    description: 'Find the facts and the remainders.',
    example: '65 ÷ 6 = (6 × 10) + 5'
  },
  {
    id: CategoryType.FRACTIONS,
    title: 'Fraction Power',
    icon: '🧩',
    color: 'bg-purple-600',
    description: 'Halves, Quarters, and Three Quarters.',
    example: 'Quarter of 80 = 80 ÷ 4 = 20'
  },
  {
    id: CategoryType.ESTIMATION,
    title: 'Estimation Champ',
    icon: '🔢',
    color: 'bg-orange-600',
    description: 'Build your "Number Sense".',
    example: '49 + 73 ≈ 50 + 70 = 120'
  }
];

// ── Badge catalog: Spooky Study + Galaxy Lab sets ──
export const STUFFY_BADGES: StuffyBadge[] = [
  // Spooky Study Set
  {
    id: 'milk_teeth_medal',
    setId: 'spooky_study',
    name: 'Milk Teeth Medal',
    slot: 'body',
    rarity: 'common',
    description: 'A chunky milk-tooth necklace that clacks when you move.',
    lore: 'You bit into math for the first time.',
    emoji: '🦷',
  },
  {
    id: 'brain_melt_marshmallow_lv1',
    setId: 'spooky_study',
    name: 'Brain Melt Marshmallow',
    slot: 'body',
    rarity: 'common',
    description: 'A slightly burnt marshmallow stuck to your head, looking tired but proud.',
    lore: 'Your brain melted a little, but you stayed.',
    emoji: '🍡',
    evolvesTo: 'brain_melt_marshmallow_lv2',
  },
  {
    id: 'brain_melt_marshmallow_lv2',
    setId: 'spooky_study',
    name: 'Brain Melt Marshmallow (Double Stack)',
    slot: 'body',
    rarity: 'rare',
    description: 'Two stacked marshmallows: one sleepy, one hyper.',
    lore: 'You’ve stayed in the fire long enough to toast a friend.',
    emoji: '🍢',
    evolvesTo: 'brain_melt_marshmallow_lv3',
  },
  {
    id: 'brain_melt_marshmallow_lv3',
    setId: 'spooky_study',
    name: 'Marshmallow Crown',
    slot: 'head',
    rarity: 'rare',
    description: 'A full ring of marshmallows hovering like a halo.',
    lore: 'Your study sessions are a campfire that never goes out.',
    emoji: '👑',
  },
  {
    id: 'night_owl_crown',
    setId: 'spooky_study',
    name: 'Night Owl Crown',
    slot: 'head',
    rarity: 'rare',
    description: 'A crooked crown made of bitten crescent moons and sleepy stars.',
    lore: 'You kept the lights on when everyone else went to sleep.',
    emoji: '🦉',
  },
  {
    id: 'chaos_eyes',
    setId: 'spooky_study',
    name: 'Chaos Eyes',
    slot: 'face',
    rarity: 'rare',
    description: 'One spiral eye, one star eye, always a bit jittery.',
    lore: 'You kept going even when your brain felt scrambled.',
    emoji: '👀',
  },
  {
    id: 'oopsie_bandage',
    setId: 'spooky_study',
    name: 'Oopsie Bandage',
    slot: 'body',
    rarity: 'common',
    description: 'A big bandage with a doodled smiley slapped across your cheek.',
    lore: 'Falling on your face is still moving forward.',
    emoji: '🩹',
  },
  {
    id: 'slice_and_dice_halo',
    setId: 'spooky_study',
    name: 'Slice & Dice Halo',
    slot: 'aura',
    rarity: 'rare',
    description: 'A halo of pizza, fruit, and cake slices orbiting your head.',
    lore: 'You cut every fraction into perfect pieces.',
    emoji: '🍕',
  },
  {
    id: 'shadow_study_buddy',
    setId: 'spooky_study',
    name: 'Shadow Study Buddy',
    slot: 'aura',
    rarity: 'secret',
    description: 'A tiny shadow-double that follows a frame behind you.',
    lore: 'Another you also shows up when it’s hard.',
    emoji: '👥',
  },

  // Galaxy Lab Set
  {
    id: 'starlight_goggles',
    setId: 'galaxy_lab',
    name: 'Starlight Goggles',
    slot: 'face',
    rarity: 'common',
    description: 'Glowing goggles that let you see patterns in the stars.',
    lore: 'You started looking past the answer to see the structure.',
    emoji: '🥽',
  },
  {
    id: 'orbiting_notebook',
    setId: 'galaxy_lab',
    name: 'Orbiting Notebook',
    slot: 'aura',
    rarity: 'rare',
    description: 'A tiny notebook that orbits you, pages flipping on its own.',
    lore: 'Every hard problem left a satellite note behind.',
    emoji: '📔',
  },
  {
    id: 'gravity_boots',
    setId: 'galaxy_lab',
    name: 'Gravity Boots',
    slot: 'body',
    rarity: 'common',
    description: 'Heavy boots that keep you grounded in long, tough sets.',
    lore: 'You didn’t float away when the problems got heavy.',
    emoji: '🥾',
  },
  {
    id: 'quantum_pocket_watch',
    setId: 'galaxy_lab',
    name: 'Quantum Pocket Watch',
    slot: 'body',
    rarity: 'rare',
    description: 'A watch that ticks faster when you think faster.',
    lore: 'You bent time by staying accurate at speed.',
    emoji: '⌚️',
  },
  {
    id: 'nebula_coat',
    setId: 'galaxy_lab',
    name: 'Nebula Coat',
    slot: 'body',
    rarity: 'rare',
    description: 'A lab coat made of swirling nebula clouds.',
    lore: 'You solved enough problems to make your own constellation.',
    emoji: '🧥',
  },
  {
    id: 'black_hole_backpack',
    setId: 'galaxy_lab',
    name: 'Black Hole Backpack',
    slot: 'body',
    rarity: 'secret',
    description: 'A backpack that swallows all your mistakes into tiny stars.',
    lore: 'Every error became fuel for something brighter.',
    emoji: '🎒',
  },
  {
    id: 'comet_tail_aura',
    setId: 'galaxy_lab',
    name: 'Comet Tail',
    slot: 'aura',
    rarity: 'rare',
    description: 'A bright comet tail that follows every time you move.',
    lore: 'Your streak burned a path across the sky.',
    emoji: '☄️',
  },
  {
    id: 'alien_theorem_hat',
    setId: 'galaxy_lab',
    name: 'Alien Theorem Hat',
    slot: 'head',
    rarity: 'secret',
    description: 'A squishy alien thinking cap with glowing symbols.',
    lore: 'You solved enough hard puzzles that something from elsewhere took notice.',
    emoji: '👽',
  },

  // Forest Friends Set
  {
    id: 'acorn_helm',
    setId: 'forest_friends',
    name: 'Acorn Helm',
    slot: 'head',
    rarity: 'common',
    description: 'A tiny acorn helmet with a leaf visor and snug chin strap.',
    lore: 'You started your adventure under the oak tree.',
    emoji: '🌰',
  },
  {
    id: 'mossy_mittens',
    setId: 'forest_friends',
    name: 'Mossy Mittens',
    slot: 'body',
    rarity: 'common',
    description: 'Soft mittens that smell like fresh rain on stone.',
    lore: 'You kept your hands steady through tricky steps.',
    emoji: '🧤',
  },
  {
    id: 'brookstream_scarf',
    setId: 'forest_friends',
    name: 'Brookstream Scarf',
    slot: 'body',
    rarity: 'rare',
    description: 'A ribbon scarf that flows like a quiet creek.',
    lore: 'You followed every number to its calm ending.',
    emoji: '🧣',
  },
  {
    id: 'firefly_freckles',
    setId: 'forest_friends',
    name: 'Firefly Freckles',
    slot: 'face',
    rarity: 'rare',
    description: 'Glowing freckles that blink on when you smile.',
    lore: 'Your joy lit up the night practice.',
    emoji: '✨',
  },
  {
    id: 'fern_glow_aura',
    setId: 'forest_friends',
    name: 'Fern Glow Aura',
    slot: 'aura',
    rarity: 'rare',
    description: 'A ring of ferns that hums with forest light.',
    lore: 'You grew patience with every problem.',
    emoji: '🌿',
  },
  {
    id: 'starfall_antlers',
    setId: 'forest_friends',
    name: 'Starfall Antlers',
    slot: 'head',
    rarity: 'secret',
    description: 'Gentle antlers dusted with tiny falling stars.',
    lore: 'The forest crowned your mastery with starlight.',
    emoji: '🦌',
  },

  // Candy Workshop Set
  {
    id: 'candy_crown',
    setId: 'candy_workshop',
    name: 'Candy Crown',
    slot: 'head',
    rarity: 'common',
    description: 'A peppermint crown with glossy sugar jewels.',
    lore: 'You earned your first sweet victory.',
    emoji: '🍬',
  },
  {
    id: 'sprinkle_specs',
    setId: 'candy_workshop',
    name: 'Sprinkle Specs',
    slot: 'face',
    rarity: 'common',
    description: 'Bright sprinkle glasses that sharpen your focus.',
    lore: 'Every detail tasted a little sweeter.',
    emoji: '🍭',
  },
  {
    id: 'gumdrop_gloves',
    setId: 'candy_workshop',
    name: 'Gumdrop Gloves',
    slot: 'body',
    rarity: 'common',
    description: 'Squishy gloves that bounce back from mistakes.',
    lore: 'You kept going with sticky determination.',
    emoji: '🧤',
  },
  {
    id: 'frosting_armor',
    setId: 'candy_workshop',
    name: 'Frosting Armor',
    slot: 'body',
    rarity: 'rare',
    description: 'Swirls of frosting that sparkle like snow.',
    lore: 'You stayed cool under every challenge.',
    emoji: '🧁',
  },
  {
    id: 'caramel_cape',
    setId: 'candy_workshop',
    name: 'Caramel Cape',
    slot: 'body',
    rarity: 'rare',
    description: 'A flowing cape with a warm caramel glow.',
    lore: 'Your kindness warmed up the whole room.',
    emoji: '🍮',
  },
  {
    id: 'lollipop_lens',
    setId: 'candy_workshop',
    name: 'Lollipop Lens',
    slot: 'face',
    rarity: 'rare',
    description: 'A swirled monocle that spots patterns fast.',
    lore: 'You learned to see the spin in every problem.',
    emoji: '🍭',
  },
  {
    id: 'taffy_tail_aura',
    setId: 'candy_workshop',
    name: 'Taffy Tail Aura',
    slot: 'aura',
    rarity: 'rare',
    description: 'A ribbon of taffy that loops around you.',
    lore: 'Your practice stretched farther each day.',
    emoji: '🎀',
  },
  {
    id: 'sugar_comet',
    setId: 'candy_workshop',
    name: 'Sugar Comet',
    slot: 'aura',
    rarity: 'secret',
    description: 'A bright candy comet that zips in happy spirals.',
    lore: 'You sparked a streak of delicious wins.',
    emoji: '☄️',
  },

  // Ocean Voyage Set
  {
    id: 'captain_shell_hat',
    setId: 'ocean_voyage',
    name: 'Captain Shell Hat',
    slot: 'head',
    rarity: 'common',
    description: 'A shell captain hat with a tiny anchor pin.',
    lore: 'You charted your first course.',
    emoji: '🐚',
  },
  {
    id: 'kelp_mask',
    setId: 'ocean_voyage',
    name: 'Kelp Mask',
    slot: 'face',
    rarity: 'common',
    description: 'A seaweed mask that keeps your eyes steady.',
    lore: 'You stayed calm through the waves.',
    emoji: '🌊',
  },
  {
    id: 'tide_traveler_vest',
    setId: 'ocean_voyage',
    name: 'Tide Traveler Vest',
    slot: 'body',
    rarity: 'common',
    description: 'A padded vest for long voyages.',
    lore: 'You kept afloat in the tricky parts.',
    emoji: '🦺',
  },
  {
    id: 'coral_charm',
    setId: 'ocean_voyage',
    name: 'Coral Charm',
    slot: 'body',
    rarity: 'rare',
    description: 'A coral charm that glows when you solve fast.',
    lore: 'Your answers bloomed bright.',
    emoji: '🪸',
  },
  {
    id: 'seaglass_scarf',
    setId: 'ocean_voyage',
    name: 'Seaglass Scarf',
    slot: 'body',
    rarity: 'rare',
    description: 'A scarf that shimmers like polished sea glass.',
    lore: 'You smoothed out every rough edge.',
    emoji: '🧣',
  },
  {
    id: 'starfish_smile',
    setId: 'ocean_voyage',
    name: 'Starfish Smile',
    slot: 'face',
    rarity: 'rare',
    description: 'A starfish grin that never quits.',
    lore: 'You kept your spirits bright.',
    emoji: '⭐️',
  },
  {
    id: 'bubble_blast_aura',
    setId: 'ocean_voyage',
    name: 'Bubble Blast Aura',
    slot: 'aura',
    rarity: 'rare',
    description: 'A cloud of bubbles that pop with every cheer.',
    lore: 'You celebrated each tiny win.',
    emoji: '🫧',
  },
  {
    id: 'moonlit_tide_aura',
    setId: 'ocean_voyage',
    name: 'Moonlit Tide Aura',
    slot: 'aura',
    rarity: 'secret',
    description: 'A moonlit tide that glides beside you.',
    lore: 'You navigated by patience and glow.',
    emoji: '🌙',
  },
  {
    id: 'deepsea_crown',
    setId: 'ocean_voyage',
    name: 'Deepsea Crown',
    slot: 'head',
    rarity: 'secret',
    description: 'A crown with pearls drawn from the deep.',
    lore: 'You conquered the deepest challenges.',
    emoji: '👑',
  },
];
